Learning-Fuze/c918_uberquizlet

project_setup/mern_setup/client/src/components/backEditMode.js
project_setup/mern_setup/client/src/components/displayFront.js
project_setup/mern_setup/client/src/components/frontEditMode.js

- completed the display of the back and front text of the edit modes into a text area

completed the get's for the edit mode

---

project_setup/mern_setup/server/server.js

Post Endpoints

---

project_setup/mern_setup/client/src/actions/index.js
project_setup/mern_setup/client/src/actions/types.js
project_setup/mern_setup/client/src/components/flashcardGeneration.js
project_setup/mern_setup/client/src/reducers/card_reducer.js
project_setup/mern_setup/client/src/reducers/index.js

- completed the displaying of all the flashcards

finished flashcard generation

---

project_setup/mern_setup/client/src/components/displayBack.js
project_setup/mern_setup/client/src/components/flashcardGeneration.js

- completed displaying subcategory
- completed spinner

added spinner to flashcard generation

---

project_setup/mern_setup/client/dist/index.html
project_setup/mern_setup/client/src/assets/css/logIn.css
project_setup/mern_setup/client/src/assets/css/nav_bar.css
project_setup/mern_setup/client/src/components/logIn.js
project_setup/mern_setup/client/src/components/nav_bar.js

- finished log in css
- made the page responsive

completed log in css

---

project_setup/mern_setup/client/src/actions/index.js
project_setup/mern_setup/client/src/components/displayCard.js
project_setup/mern_setup/client/src/reducers/sets_reducer.js

- able to get card front and back to display

completed displaying card functionality

---

project_setup/mern_setup/client/src/actions/index.js
project_setup/mern_setup/client/src/components/app.js
project_setup/mern_setup/client/src/components/displayCard.js
project_setup/mern_setup/client/src/components/editMode.js
project_setup/mern_setup/client/src/components/flashcardGeneration.js
project_setup/mern_setup/client/src/components/sets.js
project_setup/mern_setup/client/src/reducers/sets_reducer.js

- we created multiple flashcards
- able to get data from the same reducer and changed to dispatch

able to get multiple flashcards to generate

---

client/src/actions/index.js
client/src/components/profile.js

completed category deletion

---

client/src/actions/index.js
client/src/actions/types.js
client/src/components/flashcardGeneration.js
client/src/components/sets.js
client/src/reducers/sets_reducer.js

- completed delete functionality on sets

Set delete

---

client/src/actions/index.js
client/src/components/modal.js
client/src/components/sets.js

- completed basic functionality of adding a new set through a modal

completed adding sets modal

---

client/src/assets/css/nav_bar.css
client/src/assets/css/profile.css
client/src/components/nav_bar.js
client/src/components/profile.js
client/src/components/sign-up.js

- added profile info into side nav
- made side nav max width
- general css revisions on profile and side nav

Apply avatar and name to side nav

---

client/src/components/flashcardGeneration.js
client/src/components/inputDefinition.js
client/src/components/nav_bar.js

- fixed the flashcard preview displays to display the substring if length too long
- centered sign out button on side nav

fixed substring limits for flashcard displays

---

client/src/components/inputDefinition.js

- form validation on term and definition inputs

basic form validation for term and definition

---

client/src/components/flashcardGeneration.js
server.js

- completed flash card generation delete modal

Card delete

---

client/src/assets/css/dropdown.css
client/src/components/sign-up.js

- created a default value for users to pick
- refined email error regex to allow special characters

Sign up page

---

client/src/components/sets.js

- fixed subcategory delete functonality

fixed subcategory functionality

---

client/src/components/sets.js

- completed rerouting when there are zero terms.

completed rerouting

---

client/src/assets/css/dropdown.css
client/src/components/sign-up.js

- revised dropdown menu css
- added a preview for users when clicking on an avatar selection in signup page

Dropdown menu

---

client/src/actions/index.js
client/src/components/sign-in.js

- an error message appears if the entered email or pw isn't an existing user

Error message for invalid email/pw

---

client/src/actions/index.js
client/src/actions/types.js
client/src/components/profile.js
client/src/reducers/user_reducer.js
server.js

- patch endpoint allows user to change avatar on profile page

created a backend patch endpoint to update the user avatar.

---

client/src/components/editMode.js

- changed the cancel modal so that the no redirects you back to the flashcard list page

completed no functionality

---

client/src/components/flashcardGeneration.js

- finished basic infinite scroll functionality
- need to still work on adding loading spinner or indicator

created infinite scroll functionality

---

client/src/components/flashcardGeneration.js

- infinite scroll function now has a loading bar for user's to see their cards being loaded onto the DOM
- fixed issue of loading bar appearing even though all cards have been displayed.

Inifinte scroll

---

client/src/assets/css/basic_modal.css
client/src/assets/css/modal.css
client/src/components/flashcardGeneration.js
client/src/components/inputDefinition.js
client/src/components/modal.js
client/src/components/sets.js

- created basic validation for modals

Input validation for modals

---

client/src/components/app.js
client/src/components/logIn.js
client/src/hoc/auth.js

- If you are authorized/signed in, it takes you to the profile page
- if not, you'll be taken to the landing page

fixed routing to go to landing page if not authorized

---

client/src/actions/index.js
client/src/components/sign-in.js
client/src/components/sign-up.js
client/src/reducers/user_reducer.js

adding confirm password section, adding click handler onto dropdown viewing area, validation error texts showing correctly

Sign Up Page Validation Errors Display

---

client/src/components/modal.js
client/src/components/profile.js

- inputs section shows correct errors

fixed errors not showing up on profile modals

---

client/src/components/modal.js
client/src/components/sets.js

- fixed bug that allowed user to make empty category/subcategories

fixed redux form bug

---

client/src/assets/css/card.css
client/src/assets/css/flashcardGeneration.css
client/src/assets/css/profile.css
client/src/components/displayCard.js
client/src/components/flashcardGeneration.js
client/src/components/inputDefinition.js
client/src/components/profile.js
client/src/components/sets.js

- fixed text overflowing in cards, preview of cards, and containers

Fixing text overflow

---

client/src/components/displayCard.js

- when using cards, you can flip them and go through them using left arrow, right arrow, and spacebar

adding keypress functionality
